/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.form;

/**
 *
 * @author Admin
 */
public class formThongTinNCC extends javax.swing.JDialog {

    /**
     * Creates new form ThongTinNCC
     */
    public formThongTinNCC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundPanel1 = new Swing.RoundPanel();
        topRoundedPanel1 = new Swing.TopRoundedPanel();
        lblSuaNCC = new javax.swing.JLabel();
        bottomRoundedPanel1 = new Swing.BottomRoundedPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txtHoTen4 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txtHoTen3 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        txtHoTen5 = new javax.swing.JTextField();
        bottomRoundedPanel2 = new Swing.BottomRoundedPanel();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(81, 219, 185));
        jPanel1.setPreferredSize(new java.awt.Dimension(634, 464));

        roundPanel1.setBackground(new java.awt.Color(0, 120, 92));
        roundPanel1.setPreferredSize(new java.awt.Dimension(569, 464));
        roundPanel1.setLayout(new java.awt.BorderLayout());

        topRoundedPanel1.setPreferredSize(new java.awt.Dimension(569, 75));
        topRoundedPanel1.setLayout(new java.awt.BorderLayout());

        lblSuaNCC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSuaNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSuaNCC.setText("Thông tin nhà cung cấp");
        lblSuaNCC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSuaNCC.setMaximumSize(new java.awt.Dimension(190, 32));
        lblSuaNCC.setMinimumSize(new java.awt.Dimension(190, 32));
        lblSuaNCC.setPreferredSize(new java.awt.Dimension(190, 32));
        topRoundedPanel1.add(lblSuaNCC, java.awt.BorderLayout.CENTER);

        roundPanel1.add(topRoundedPanel1, java.awt.BorderLayout.PAGE_START);

        bottomRoundedPanel1.setPreferredSize(new java.awt.Dimension(569, 325));
        bottomRoundedPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(567, 350));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel8.setPreferredSize(new java.awt.Dimension(567, 87));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Mã nhà cung cấp:");
        jLabel6.setAlignmentX(20.0F);
        jLabel6.setAlignmentY(20.0F);
        jPanel13.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel13, java.awt.BorderLayout.LINE_START);

        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 30);
        flowLayout3.setAlignOnBaseline(true);
        jPanel10.setLayout(flowLayout3);

        txtHoTen4.setPreferredSize(new java.awt.Dimension(350, 22));
        jPanel10.add(txtHoTen4);

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8);

        jPanel6.setPreferredSize(new java.awt.Dimension(567, 87));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel14.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Địa chỉ:");
        jPanel14.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel14, java.awt.BorderLayout.LINE_START);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 30));

        txtHoTen3.setPreferredSize(new java.awt.Dimension(350, 22));
        jPanel9.add(txtHoTen3);

        jPanel6.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel11.setPreferredSize(new java.awt.Dimension(567, 87));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel15.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Địa chỉ:");
        jPanel15.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel15, java.awt.BorderLayout.LINE_START);

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 30));

        txtHoTen5.setPreferredSize(new java.awt.Dimension(350, 22));
        jPanel18.add(txtHoTen5);

        jPanel11.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel11);

        bottomRoundedPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        bottomRoundedPanel2.setPreferredSize(new java.awt.Dimension(567, 80));
        bottomRoundedPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 150, 25));

        btnHuy.setBackground(new java.awt.Color(255, 103, 102));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ");
        btnHuy.setPreferredSize(new java.awt.Dimension(90, 35));
        bottomRoundedPanel2.add(btnHuy);

        bottomRoundedPanel1.add(bottomRoundedPanel2, java.awt.BorderLayout.PAGE_END);

        roundPanel1.add(bottomRoundedPanel1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 26, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 27, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formThongTinNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formThongTinNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formThongTinNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formThongTinNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                formThongTinNCC dialog = new formThongTinNCC(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.BottomRoundedPanel bottomRoundedPanel1;
    private Swing.BottomRoundedPanel bottomRoundedPanel2;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblSuaNCC;
    private Swing.RoundPanel roundPanel1;
    private Swing.TopRoundedPanel topRoundedPanel1;
    private javax.swing.JTextField txtHoTen3;
    private javax.swing.JTextField txtHoTen4;
    private javax.swing.JTextField txtHoTen5;
    // End of variables declaration//GEN-END:variables
}
