/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.page.ThongKe;

import DAO.ThongKeDAO;
import Entity.ThongKeTheoNam;
import GUI.barchart.ModelChart;
import Utils.Formatter;
import Utils.MessageDialog;
import Utils.TableSorter;
import Utils.Validation;
import java.awt.Color;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roxan
 */
public class frmThongKeDoanhThuTheoNamPage extends javax.swing.JPanel {

    /**
     * Creates new form frmThongKeDoanhThuTheoNamPage
     */
    private final int currentYear = LocalDate.now().getYear();
    private List<ThongKeTheoNam> listTK;
    private DefaultTableModel modal;
    private ThongKeDAO thongKeDAO;

    public frmThongKeDoanhThuTheoNamPage() {
        initComponents();
        thongKeDAO = new ThongKeDAO();  // Khởi tạo ThongKeDAO để truy vấn trực tiếp
        chartLayout();
        tableLayout();
        loadDataset();
    }

    // Thiết lập biểu đồ
    private void chartLayout() {
        chart.addLegend("Doanh thu", new Color(135, 189, 245));
        chart.addLegend("Chi phí", new Color(245, 189, 135));
        chart.addLegend("Lợi nhuận", new Color(139, 225, 196));
        chart.start();
    }

    // Tải dữ liệu vào biểu đồ
    private void loadChart() {
        for (ThongKeTheoNam e : listTK) {
            chart.addData(new ModelChart("Năm " + e.getNam(), new double[]{e.getDoanhThu(), e.getChiPhi(), e.getLoiNhuan()}));
        }
    }

    // Thiết lập bảng
    private void tableLayout() {
        String[] header = new String[]{"Năm", "Doanh thu", "Chi phí", "Lợi nhuận"};
        modal = new DefaultTableModel();
        modal.setColumnIdentifiers(header);
        table.setModel(modal);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        table.setDefaultRenderer(Object.class, centerRenderer);
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        table.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        table.getColumnModel().getColumn(0).setPreferredWidth(30);

        sortTable();
    }

    // Sắp xếp bảng
    private void sortTable() {
        table.setAutoCreateRowSorter(true);
        TableSorter.configureTableColumnSorter(table, 0, TableSorter.STRING_COMPARATOR);
    }

    // Tải dữ liệu vào bảng
    private void loadTable() {
        modal.setRowCount(0);
        for (ThongKeTheoNam e : listTK) {
            modal.addRow(new Object[]{
                e.getNam() + "", Formatter.FormatVND(e.getDoanhThu()), Formatter.FormatVND(e.getChiPhi()), Formatter.FormatVND(e.getLoiNhuan())
            });
        }
    }

    // Tải dữ liệu thống kê (biểu đồ và bảng)
    private void loadDataset() {
        chart.clear();
        int startYear = Integer.parseInt(txtStartYear.getText()); // Năm bắt đầu
        int endYear = Integer.parseInt(txtEndYear.getText()); // Năm kết thúc
        listTK = thongKeDAO.selectFromYearToYear(startYear, endYear);  // Truy vấn trực tiếp trong DAO
        loadChart();
        loadTable();
        chart.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lblChart = new javax.swing.JLabel();
        txtStartYear = new javax.swing.JTextField();
        lblChart1 = new javax.swing.JLabel();
        txtEndYear = new javax.swing.JTextField();
        btnStatistic = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        chart = new GUI.barchart.chart();

        setMinimumSize(new java.awt.Dimension(1130, 800));
        setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(247, 247, 247));
        jPanel5.setPreferredSize(new java.awt.Dimension(1188, 30));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 0));

        lblChart.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblChart.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChart.setText("Từ năm");
        lblChart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblChart.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel5.add(lblChart);

        txtStartYear.setText("2015");
        jPanel5.add(txtStartYear);

        lblChart1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblChart1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChart1.setText("Đến năm");
        lblChart1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblChart1.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel5.add(lblChart1);

        txtEndYear.setText("2025");
        txtEndYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndYearActionPerformed(evt);
            }
        });
        jPanel5.add(txtEndYear);

        btnStatistic.setBackground(new java.awt.Color(51, 153, 255));
        btnStatistic.setForeground(new java.awt.Color(204, 255, 255));
        btnStatistic.setText("Thống kê");
        btnStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticActionPerformed(evt);
            }
        });
        jPanel5.add(btnStatistic);

        add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(456, 300));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Họ tên", "Số điện thoại", "Giới tính", "Năm sinh", "Ngày vào làm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFocusable(false);
        table.setRowHeight(40);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, java.awt.BorderLayout.SOUTH);
        add(chart, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
private boolean isValidFilterFields() {
        if (Validation.isEmpty(txtStartYear.getText().trim())) {
            MessageDialog.warring(this, "Không được để trống!");
            Validation.resetTextfield(txtStartYear);
            return false;
        }
        if (Validation.isEmpty(txtEndYear.getText().trim())) {
            MessageDialog.warring(this, "Không được để trống!");
            Validation.resetTextfield(txtEndYear);
            return false;
        }

        int fromYear = Integer.parseInt(txtStartYear.getText());
        int toYear = Integer.parseInt(txtEndYear.getText());

        try {
            if (fromYear <= 1900 || fromYear > currentYear
                    && toYear <= 1900 || toYear > currentYear) {
                MessageDialog.warring(this, "Số năm phải từ 1900 đến " + currentYear);
                return false;
            }
            if (toYear < fromYear) {
                MessageDialog.warring(this, "Số năm kết thúc phải >= năm bắt đầu!");
                Validation.selectAllTextfield(txtEndYear);
                return false;
            }
            if (toYear - fromYear >= 10) {
                MessageDialog.warring(this, "Hai năm không cách nhau quá 10 năm");
                Validation.selectAllTextfield(txtStartYear);
                return false;
            }
        } catch (NumberFormatException e) {
            MessageDialog.warring(this, "Số không hợp lệ!");
            Validation.resetTextfield(txtStartYear);
            return false;
        }

        return true;
    }
    private void btnStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticActionPerformed
        if (isValidFilterFields()) {
            int startYear = Integer.parseInt(txtStartYear.getText());
            int endYear = Integer.parseInt(txtEndYear.getText());
            listTK = thongKeDAO.selectFromYearToYear(startYear, endYear); // Truy vấn trực tiếp trong DAO
            loadDataset();
        }
    }//GEN-LAST:event_btnStatisticActionPerformed

    private void txtEndYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndYearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStatistic;
    private GUI.barchart.chart chart;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChart;
    private javax.swing.JLabel lblChart1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtEndYear;
    private javax.swing.JTextField txtStartYear;
    // End of variables declaration//GEN-END:variables
}
