/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.page;

import DAO.NhaCungCapDAO;
import Entity.NhaCungCap;
import GUI.form.formSuaNCC;
import GUI.form.formThemNCC;
import java.util.List;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class frmNhaCungCapCapNhat extends javax.swing.JPanel {

    /**
     * Creates new form NhaCungCapCapNhat
     */
    public frmNhaCungCapCapNhat() {
        initComponents();
        btnThem.addActionListener(evt -> openFormThemNCC());
        btnSua.addActionListener(evt -> openFormSuaNCC());
        loadTableData();
    }
private void openFormThemNCC() {
    JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    formThemNCC dialog = new formThemNCC(parentFrame, true);
    dialog.setLocationRelativeTo(this); 
    dialog.setVisible(false); 
}

private void openFormSuaNCC() {
    JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    formSuaNCC dialog = new formSuaNCC(parentFrame, true);
    dialog.setLocationRelativeTo(this); 
    dialog.setVisible(false); 
}
    private void loadTableData() {
         // Lấy tất cả nhân viên từ cơ sở dữ liệu
         List<NhaCungCap> danhSachNhaCungCap = NhaCungCapDAO.getAllNhaCungCap();
 
         // Tạo DefaultTableModel với các cột
         String[] columnNames = {"Mã NCC", "Tên NCC", "Địa chỉ NCC", "SĐT"};
         DefaultTableModel model = new DefaultTableModel(columnNames, 0);
 
         // Thêm từng nhân viên vào bảng
         for (NhaCungCap ncc : danhSachNhaCungCap) {
             Object[] rowData = {
                 ncc.getId(),
                 ncc.getTenNhaCungCap(),
                 ncc.getDiaChi(),
                 ncc.getSdt()                 
             };
             model.addRow(rowData);  // Thêm dòng vào model
         }
         jTable1.setDefaultEditor(Object.class, null);
 
         // Gán DefaultTableModel cho JTable
         jTable1.setModel(model);  // jTable1 là JTable trên form của bạn
         DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
         centerRenderer.setHorizontalAlignment(JLabel.CENTER);
         for (int i = 0; i < jTable1.getColumnCount(); i++) {
             jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnPanel = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        jLabel7.setBackground(new java.awt.Color(0, 120, 92));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Danh sách nhà cung cấp");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setMaximumSize(new java.awt.Dimension(829, 600));
        setMinimumSize(new java.awt.Dimension(829, 600));
        setPreferredSize(new java.awt.Dimension(829, 600));
        setLayout(new java.awt.BorderLayout());

        tablePanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 120, 92));
        jPanel1.setMinimumSize(new java.awt.Dimension(829, 50));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(829, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thông tin nhà cung cấp");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        tablePanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã NCC", "Tên NCC", "Địa chỉ NCC", "SĐT NCC"
            }
        ));
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(jTable1);

        tablePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(tablePanel, java.awt.BorderLayout.CENTER);

        btnPanel.setBackground(new java.awt.Color(222, 222, 222));
        btnPanel.setPreferredSize(new java.awt.Dimension(829, 50));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 8);
        flowLayout1.setAlignOnBaseline(true);
        btnPanel.setLayout(flowLayout1);

        btnThem.setBackground(new java.awt.Color(0, 120, 92));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setMaximumSize(new java.awt.Dimension(85, 35));
        btnThem.setMinimumSize(new java.awt.Dimension(85, 35));
        btnThem.setPreferredSize(new java.awt.Dimension(105, 35));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        btnPanel.add(btnThem);

        btnSua.setBackground(new java.awt.Color(0, 120, 92));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSua.setMaximumSize(new java.awt.Dimension(85, 35));
        btnSua.setMinimumSize(new java.awt.Dimension(85, 35));
        btnSua.setPreferredSize(new java.awt.Dimension(105, 35));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        btnPanel.add(btnSua);

        btnXoa.setBackground(new java.awt.Color(0, 120, 92));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xoá");
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa.setMaximumSize(new java.awt.Dimension(85, 35));
        btnXoa.setMinimumSize(new java.awt.Dimension(85, 35));
        btnXoa.setPreferredSize(new java.awt.Dimension(105, 35));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        btnPanel.add(btnXoa);

        add(btnPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
         formThemNCC dialog = new formThemNCC(parentFrame, true);  // Mở formThemNV
         dialog.setLocationRelativeTo(this);
         dialog.setVisible(true);
 
         // Sau khi đóng formThemNV, gọi lại phương thức để làm mới bảng
         loadTableData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        
         int selectedRow = jTable1.getSelectedRow();
         if (selectedRow != -1) {
             String maNCC = jTable1.getValueAt(selectedRow, 0).toString();  // Lấy mã nhân viên từ cột đầu tiên
 
             // Mở form sửa nhân viên và truyền mã nhân viên vào constructor
             JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
             formSuaNCC dialog = new formSuaNCC(parentFrame, true, maNCC);  // Truyền mã nhân viên vào constructor
             dialog.setLocationRelativeTo(this);
             dialog.setVisible(true);
             loadTableData();
         } else {
             JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà cung cấp để sửa!");
         }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
         if (selectedRow != -1) {
             String maNCC = jTable1.getValueAt(selectedRow, 0).toString();  // Lấy mã nhân viên từ cột đầu tiên
 
             // Hiển thị hộp thoại xác nhận xóa
             int response = JOptionPane.showConfirmDialog(this,
                     "Bạn có chắc chắn muốn xóa nhân viên này?",
                     "Xác nhận", JOptionPane.YES_NO_OPTION);
 
             // Nếu người dùng chọn Yes, thực hiện xóa
             if (response == JOptionPane.YES_OPTION) {
                 // Gọi hàm xóa nhân viên trong DAO
                 if (NhaCungCapDAO.xoa(maNCC)) {
                     JOptionPane.showMessageDialog(this, "Xóa nhà cung cấp thành công!");
                     loadTableData();  // Làm mới bảng sau khi xóa
                 } else {
                     JOptionPane.showMessageDialog(this, "Xóa nhà cung cấp thất bại!");
                 }
             }
         } else {
             JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà cung cấp để xóa!");
         }
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables
}
