/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.page;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Admin
 */
public class frmNhaCungCapCapNhat extends javax.swing.JPanel {

    /**
     * Creates new form NhaCungCapCapNhat
     */
    public frmNhaCungCapCapNhat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnPanel = new javax.swing.JPanel();
        btnThemNCC = new javax.swing.JButton();
        btnSuaNCC = new javax.swing.JButton();
        btnXoaNCC = new javax.swing.JButton();

        jLabel7.setBackground(new java.awt.Color(0, 120, 92));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Danh sách nhà cung cấp");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setMaximumSize(new java.awt.Dimension(829, 600));
        setMinimumSize(new java.awt.Dimension(829, 600));
        setPreferredSize(new java.awt.Dimension(829, 600));
        setLayout(new java.awt.BorderLayout());

        tablePanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(829, 50));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(829, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thông tin nhà cung cấp");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        tablePanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã NCC", "Tên NCC", "Địa chỉ NCC", "SĐT NCC"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(jTable1);

        tablePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(tablePanel, java.awt.BorderLayout.CENTER);

        btnPanel.setBackground(new java.awt.Color(222, 222, 222));
        btnPanel.setPreferredSize(new java.awt.Dimension(829, 50));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 8);
        flowLayout3.setAlignOnBaseline(true);
        btnPanel.setLayout(flowLayout3);

        btnThemNCC.setBackground(new java.awt.Color(0, 153, 153));
        btnThemNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemNCC.setForeground(new java.awt.Color(255, 255, 255));
        btnThemNCC.setText("Thêm");
        btnThemNCC.setMaximumSize(new java.awt.Dimension(85, 35));
        btnThemNCC.setMinimumSize(new java.awt.Dimension(85, 35));
        btnThemNCC.setPreferredSize(new java.awt.Dimension(85, 35));
        btnThemNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNCCActionPerformed(evt);
            }
        });
        btnPanel.add(btnThemNCC);

        btnSuaNCC.setBackground(new java.awt.Color(0, 153, 153));
        btnSuaNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaNCC.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaNCC.setText("Sửa");
        btnSuaNCC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSuaNCC.setMaximumSize(new java.awt.Dimension(85, 35));
        btnSuaNCC.setMinimumSize(new java.awt.Dimension(85, 35));
        btnSuaNCC.setPreferredSize(new java.awt.Dimension(85, 35));
        btnPanel.add(btnSuaNCC);

        btnXoaNCC.setBackground(new java.awt.Color(0, 153, 153));
        btnXoaNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaNCC.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaNCC.setText("Xoá");
        btnXoaNCC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoaNCC.setMaximumSize(new java.awt.Dimension(85, 35));
        btnXoaNCC.setMinimumSize(new java.awt.Dimension(85, 35));
        btnXoaNCC.setPreferredSize(new java.awt.Dimension(85, 35));
        btnXoaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNCCActionPerformed(evt);
            }
        });
        btnPanel.add(btnXoaNCC);

        add(btnPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemNCCActionPerformed

    private void btnXoaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaNCCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnSuaNCC;
    private javax.swing.JButton btnThemNCC;
    private javax.swing.JButton btnXoaNCC;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables
}
