/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.page;

/**
 *
 * @author Admin
 */
public class frmSearchNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form frmSearchNhanVien
     */
    public frmSearchNhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel10 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel11 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnPanel = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(829, 624));
        setPreferredSize(new java.awt.Dimension(829, 624));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(829, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(829, 350));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 120, 92));
        jPanel3.setMinimumSize(new java.awt.Dimension(829, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(829, 50));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập thông tin tìm kiếm");
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setMinimumSize(new java.awt.Dimension(829, 300));
        jPanel4.setPreferredSize(new java.awt.Dimension(829, 300));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel33.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel33.setLayout(new java.awt.BorderLayout());

        jPanel34.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel34.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel34.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Họ tên:");
        jLabel11.setMaximumSize(new java.awt.Dimension(170, 38));
        jLabel11.setMinimumSize(new java.awt.Dimension(170, 38));
        jLabel11.setPreferredSize(new java.awt.Dimension(170, 38));
        jPanel34.add(jLabel11, java.awt.BorderLayout.CENTER);

        jPanel33.add(jPanel34, java.awt.BorderLayout.LINE_START);

        jPanel35.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel35.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel35.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jTextField3.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel35.add(jTextField3);

        jPanel33.add(jPanel35, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel33);

        jPanel8.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel17.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel17.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Giới tính:");
        jLabel4.setMaximumSize(new java.awt.Dimension(170, 38));
        jLabel4.setMinimumSize(new java.awt.Dimension(170, 38));
        jLabel4.setPreferredSize(new java.awt.Dimension(170, 38));
        jPanel17.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel17, java.awt.BorderLayout.LINE_START);

        jPanel18.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel18.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jRadioButton1.setText("Nam");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel18.add(jRadioButton1);

        jRadioButton2.setText("Nữ");
        jPanel18.add(jRadioButton2);

        jPanel8.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel8);

        jPanel9.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel19.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel19.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Ngày sinh:");
        jLabel5.setMaximumSize(new java.awt.Dimension(170, 38));
        jLabel5.setMinimumSize(new java.awt.Dimension(170, 38));
        jLabel5.setPreferredSize(new java.awt.Dimension(170, 38));
        jPanel19.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel19, java.awt.BorderLayout.LINE_START);

        jPanel20.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel20.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jDateChooser1.setPreferredSize(new java.awt.Dimension(88, 30));
        jPanel20.add(jDateChooser1);

        jPanel9.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel9);

        jPanel10.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel21.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel21.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Ngày vào làm:");
        jLabel6.setMaximumSize(new java.awt.Dimension(170, 38));
        jLabel6.setMinimumSize(new java.awt.Dimension(170, 38));
        jLabel6.setPreferredSize(new java.awt.Dimension(170, 38));
        jPanel21.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel21, java.awt.BorderLayout.LINE_START);

        jPanel22.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel22.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jDateChooser2.setPreferredSize(new java.awt.Dimension(88, 30));
        jPanel22.add(jDateChooser2);

        jPanel10.add(jPanel22, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel10);

        jPanel11.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel23.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel23.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel23.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("CCCD:");
        jLabel7.setMaximumSize(new java.awt.Dimension(170, 38));
        jLabel7.setMinimumSize(new java.awt.Dimension(170, 38));
        jLabel7.setPreferredSize(new java.awt.Dimension(170, 38));
        jPanel23.add(jLabel7, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel23, java.awt.BorderLayout.LINE_START);

        jPanel24.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel24.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jTextField1.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel24.add(jTextField1);

        jPanel11.add(jPanel24, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel11);

        jPanel12.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel25.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel25.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Chức vụ:");
        jLabel8.setMaximumSize(new java.awt.Dimension(170, 38));
        jLabel8.setMinimumSize(new java.awt.Dimension(170, 38));
        jLabel8.setPreferredSize(new java.awt.Dimension(170, 38));
        jPanel25.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel25, java.awt.BorderLayout.LINE_START);

        jPanel26.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel26.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jRadioButton3.setText("Quản lý");
        jPanel26.add(jRadioButton3);

        jRadioButton4.setText("Nhân viên");
        jPanel26.add(jRadioButton4);

        jPanel12.add(jPanel26, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel12);

        jPanel13.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel27.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel27.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel27.setLayout(new java.awt.BorderLayout(5, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("SĐT:");
        jLabel9.setMaximumSize(new java.awt.Dimension(170, 38));
        jLabel9.setMinimumSize(new java.awt.Dimension(170, 38));
        jLabel9.setPreferredSize(new java.awt.Dimension(180, 38));
        jPanel27.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        jPanel13.add(jPanel27, java.awt.BorderLayout.LINE_START);

        jPanel28.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel28.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jTextField2.setMinimumSize(new java.awt.Dimension(350, 22));
        jTextField2.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel28.add(jTextField2);

        jPanel13.add(jPanel28, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel13);

        jPanel14.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel30.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel30.setPreferredSize(new java.awt.Dimension(669, 38));

        jPanel29.setMaximumSize(new java.awt.Dimension(170, 38));
        jPanel29.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel29.setPreferredSize(new java.awt.Dimension(300, 38));
        jPanel29.setLayout(new java.awt.BorderLayout());
        jPanel30.add(jPanel29);

        jPanel14.add(jPanel30, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel14);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel5.setMinimumSize(new java.awt.Dimension(829, 224));
        jPanel5.setPreferredSize(new java.awt.Dimension(829, 214));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel31.setBackground(new java.awt.Color(0, 120, 92));
        jPanel31.setPreferredSize(new java.awt.Dimension(829, 50));
        jPanel31.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Danh sách nhân viên");
        jLabel2.setToolTipText("");
        jPanel31.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel31, java.awt.BorderLayout.PAGE_START);

        jPanel32.setMinimumSize(new java.awt.Dimension(824, 174));
        jPanel32.setPreferredSize(new java.awt.Dimension(824, 174));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(824, 174));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(824, 174));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã NV", "Tên NV", "SĐT ", "Giới tính", "Ngày sinh", "Ngày vào làm", "Chức vụ"
            }
        ));
        jTable1.setMinimumSize(new java.awt.Dimension(824, 174));
        jTable1.setPreferredSize(new java.awt.Dimension(824, 174));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel32.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel32, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.CENTER);

        btnPanel.setBackground(new java.awt.Color(222, 222, 222));
        btnPanel.setPreferredSize(new java.awt.Dimension(829, 50));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 8);
        flowLayout3.setAlignOnBaseline(true);
        btnPanel.setLayout(flowLayout3);

        btnTimKiem.setBackground(new java.awt.Color(0, 120, 92));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setMaximumSize(new java.awt.Dimension(85, 35));
        btnTimKiem.setMinimumSize(new java.awt.Dimension(85, 35));
        btnTimKiem.setPreferredSize(new java.awt.Dimension(105, 35));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        btnPanel.add(btnTimKiem);

        btnChiTiet.setBackground(new java.awt.Color(0, 120, 92));
        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChiTiet.setMaximumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setMinimumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setPreferredSize(new java.awt.Dimension(105, 35));
        btnPanel.add(btnChiTiet);

        add(btnPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnTimKiem;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
