/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.page;

import DAO.HoaDonDAO;
import Entity.HoaDon;
import Entity.KhachHang;
import Entity.NhanVien;
import DAO.NhanVienDAO;
import DAO.KhachHangDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;

/**
 *
 * @author ADMIN
 */
public class frmSearchHoaDon extends javax.swing.JPanel {
    private SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    private NumberFormat currencyFormat = NumberFormat.getCurrencyInstance();

    /**
     * Creates new form frmSearchHoaDon
     */
    public frmSearchHoaDon() {
        initComponents();
        loadDataToTable();
    }

    private void loadDataToTable() {
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                // Lấy danh sách hóa đơn từ cơ sở dữ liệu
                List<HoaDon> danhSachHoaDon = HoaDonDAO.getAllHoaDon();

                SwingUtilities.invokeLater(() -> {
                    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                    model.setRowCount(0); // Xóa dữ liệu cũ trong bảng

                    int stt = 1;
                    // Thêm dữ liệu vào bảng
                    for (HoaDon hd : danhSachHoaDon) {
                        KhachHang kh = hd.getKhachHang();
                        NhanVien nv = hd.getNhanVien();

                        Object[] rowData = {
                                stt++, // Số thứ tự
                                hd.getId(), // Mã hóa đơn
                                kh != null ? kh.getHoTen() : "N/A", // Tên khách hàng
                                kh != null ? kh.getSdt() : "N/A", // SĐT
                                nv != null ? nv.getHoTen() : "N/A", // Tên nhân viên
                                dateFormat.format(hd.getNgayLap()), // Ngày mua
                                currencyFormat.format(hd.getTongTien()) // Tổng tiền
                        };
                        model.addRow(rowData); // Thêm dòng vào bảng
                    }

                    model.fireTableDataChanged(); // Đảm bảo bảng được làm mới
                    jTable2.revalidate(); // Cập nhật lại bảng
                    jTable2.repaint(); // Vẽ lại bảng
                });
                return null;
            }
        };
        worker.execute(); // Chạy dữ liệu trên một thread riêng
    }
private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
    // Lấy giá trị từ các trường nhập liệu
    String maHoaDon = textField1.getText().trim();  // Mã hóa đơn
    String tenKhachHang = textField2.getText().trim();  // Tên khách hàng
    Date ngayMua = dateNgayMua.getDate();  // Ngày mua

    // Gọi phương thức tìm kiếm với các tham số đã lấy từ UI
    SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
        @Override
        protected Void doInBackground() throws Exception {
            // Lấy danh sách hóa đơn từ cơ sở dữ liệu theo các điều kiện tìm kiếm
            List<HoaDon> danhSachHoaDon = HoaDonDAO.searchHoaDon(maHoaDon, tenKhachHang, ngayMua);

            SwingUtilities.invokeLater(() -> {
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.setRowCount(0);  // Xóa dữ liệu cũ trong bảng

                // Thêm dữ liệu mới vào bảng
                for (HoaDon hd : danhSachHoaDon) {
                    KhachHang kh = hd.getKhachHang();
                    Object[] rowData = {
                        hd.getId(),  // Mã hóa đơn
                        kh != null ? kh.getHoTen() : "N/A",  // Tên khách hàng
                        dateFormat.format(hd.getNgayLap()),  // Ngày mua
                        currencyFormat.format(hd.getTongTien())  // Tổng tiền
                    };
                    model.addRow(rowData);  // Thêm dòng vào bảng
                }

                model.fireTableDataChanged();  // Đảm bảo bảng được làm mới
                jTable2.revalidate();  // Cập nhật lại bảng
                jTable2.repaint();  // Vẽ lại bảng
            });
            return null;
        }
    };
    worker.execute();  // Chạy dữ liệu trên một thread riêng
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        textField1 = new java.awt.TextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        textField2 = new java.awt.TextField();
        jPanel17 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        dateNgayMua = new com.toedter.calendar.JDateChooser();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        btnThem2 = new javax.swing.JButton();
        btnThem3 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(829, 624));
        setMinimumSize(new java.awt.Dimension(829, 624));
        setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 102, 102));
        jPanel8.setMaximumSize(new java.awt.Dimension(829, 350));
        jPanel8.setPreferredSize(new java.awt.Dimension(829, 250));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(0, 120, 92));
        jPanel9.setMinimumSize(new java.awt.Dimension(829, 50));
        jPanel9.setPreferredSize(new java.awt.Dimension(829, 50));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nhập thông tin tìm kiếm");
        jPanel9.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setMinimumSize(new java.awt.Dimension(829, 300));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        jPanel15.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel28.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel28.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel28.setLayout(new java.awt.BorderLayout());
        jPanel15.add(jPanel28, java.awt.BorderLayout.LINE_START);

        jPanel29.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel29.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel29.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));
        jPanel15.add(jPanel29, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel15);

        jPanel21.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jPanel30.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel30.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel30.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Mã hóa đơn:");
        jLabel9.setAlignmentX(20.0F);
        jLabel9.setAlignmentY(20.0F);
        jPanel30.add(jLabel9, java.awt.BorderLayout.CENTER);

        jPanel21.add(jPanel30, java.awt.BorderLayout.LINE_START);

        jPanel31.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel31.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        textField1.setMaximumSize(new java.awt.Dimension(350, 32));
        textField1.setMinimumSize(new java.awt.Dimension(350, 32));
        textField1.setPreferredSize(new java.awt.Dimension(350, 32));
        jPanel31.add(textField1);

        jPanel21.add(jPanel31, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel21);

        jPanel14.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel26.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel26.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Tên khách hàng");
        jLabel8.setAlignmentX(20.0F);
        jLabel8.setAlignmentY(20.0F);
        jPanel26.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel26, java.awt.BorderLayout.LINE_START);

        jPanel27.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel27.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        textField2.setMaximumSize(new java.awt.Dimension(350, 32));
        textField2.setMinimumSize(new java.awt.Dimension(350, 32));
        textField2.setPreferredSize(new java.awt.Dimension(350, 32));
        jPanel27.add(textField2);

        jPanel14.add(jPanel27, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel14);

        jPanel17.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel22.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel22.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel22.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Ngày mua:");
        jLabel6.setAlignmentX(20.0F);
        jLabel6.setAlignmentY(20.0F);
        jPanel22.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel17.add(jPanel22, java.awt.BorderLayout.LINE_START);

        jPanel23.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel23.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        dateNgayMua.setMinimumSize(new java.awt.Dimension(182, 22));
        dateNgayMua.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel23.add(dateNgayMua);

        jPanel17.add(jPanel23, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel17);

        jPanel18.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel19.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel19.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel19.setLayout(new java.awt.BorderLayout());
        jPanel18.add(jPanel19, java.awt.BorderLayout.LINE_START);

        jPanel20.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel20.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));
        jPanel18.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel18);

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel12.setPreferredSize(new java.awt.Dimension(829, 220));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel33.setBackground(new java.awt.Color(0, 120, 92));
        jPanel33.setPreferredSize(new java.awt.Dimension(829, 50));
        jPanel33.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Danh sách hóa đơn");
        jPanel33.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel33, java.awt.BorderLayout.PAGE_START);

        jPanel34.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã hóa đơn", "Tên khách hàng", "SĐT", "Tên nhân viên", "Ngày mua", "Tổng hóa đơn"
            }
        ));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(jTable2);

        jPanel34.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel34, java.awt.BorderLayout.CENTER);

        add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel13.setPreferredSize(new java.awt.Dimension(829, 55));
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 10));

        btnThem2.setBackground(new java.awt.Color(0, 120, 92));
        btnThem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem2.setForeground(new java.awt.Color(255, 255, 255));
        btnThem2.setText("Tìm kiếm");
        btnThem2.setMaximumSize(new java.awt.Dimension(85, 35));
        btnThem2.setMinimumSize(new java.awt.Dimension(85, 35));
        btnThem2.setPreferredSize(new java.awt.Dimension(105, 35));
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });
        jPanel13.add(btnThem2);

        btnThem3.setBackground(new java.awt.Color(0, 120, 92));
        btnThem3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem3.setForeground(new java.awt.Color(255, 255, 255));
        btnThem3.setText("Chi tiết");
        btnThem3.setMaximumSize(new java.awt.Dimension(85, 35));
        btnThem3.setMinimumSize(new java.awt.Dimension(85, 35));
        btnThem3.setPreferredSize(new java.awt.Dimension(105, 35));
        btnThem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem3ActionPerformed(evt);
            }
        });
        jPanel13.add(btnThem3);

        add(jPanel13, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    private void btnThem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThem3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnThem3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnThem3;
    private com.toedter.calendar.JDateChooser dateNgayMua;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
