/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.page;

/**
 *
 * @author Admin
 */
public class frmSearchKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form frmSearchNhanVien
     */
    public frmSearchKhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        txtHoTen2 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        txtHoTen4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnPanel = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        txtHoTen3 = new javax.swing.JTextField();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        txtHoTen5 = new javax.swing.JTextField();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnPanel1 = new javax.swing.JPanel();
        btnTimKiem1 = new javax.swing.JButton();
        btnChiTiet1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(829, 624));
        setPreferredSize(new java.awt.Dimension(829, 624));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(829, 312));
        jPanel1.setPreferredSize(new java.awt.Dimension(829, 220));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setMinimumSize(new java.awt.Dimension(829, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(829, 50));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập thông tin tìm kiếm");
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setMinimumSize(new java.awt.Dimension(829, 300));
        jPanel4.setPreferredSize(new java.awt.Dimension(829, 150));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel19.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel19.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Họ tên:");
        jLabel3.setAlignmentX(20.0F);
        jLabel3.setAlignmentY(20.0F);
        jPanel19.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel19, java.awt.BorderLayout.LINE_START);

        jPanel20.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel20.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jTextField4.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel20.add(jTextField4);

        jPanel9.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel9);

        jPanel10.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel21.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel21.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Giới tính:");
        jPanel21.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel21, java.awt.BorderLayout.LINE_START);

        jPanel22.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel22.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 3));

        jRadioButton1.setText("Nam");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel15.add(jRadioButton1);

        jRadioButton2.setText("Nữ");
        jPanel15.add(jRadioButton2);
        jPanel15.add(jLabel9);

        jLabel5.setText("       ");
        jPanel15.add(jLabel5);

        jPanel22.add(jPanel15);

        jPanel10.add(jPanel22, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel10);

        jPanel11.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel23.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel23.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel23.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("SĐT:");
        jPanel23.add(jLabel7, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel23, java.awt.BorderLayout.LINE_START);

        jPanel24.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel24.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtHoTen2.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel24.add(txtHoTen2);

        jPanel11.add(jPanel24, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel11);

        jPanel12.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel25.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel25.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Tuổi:");
        jPanel25.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel25, java.awt.BorderLayout.LINE_START);

        jPanel26.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel26.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        txtHoTen4.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel26.add(txtHoTen4);

        jPanel12.add(jPanel26, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel12);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(829, 420));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(829, 525));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel31.setBackground(new java.awt.Color(0, 153, 153));
        jPanel31.setPreferredSize(new java.awt.Dimension(829, 50));
        jPanel31.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Danh sách khách hàng");
        jPanel31.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel31, java.awt.BorderLayout.PAGE_START);

        jPanel32.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã KH", "Tên KH", "Giới tính", "SĐT ", "Tuổi"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel32.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel32, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        btnPanel.setBackground(new java.awt.Color(222, 222, 222));
        btnPanel.setPreferredSize(new java.awt.Dimension(829, 50));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 8);
        flowLayout1.setAlignOnBaseline(true);
        btnPanel.setLayout(flowLayout1);

        btnTimKiem.setBackground(new java.awt.Color(0, 153, 153));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setMaximumSize(new java.awt.Dimension(85, 35));
        btnTimKiem.setMinimumSize(new java.awt.Dimension(85, 35));
        btnTimKiem.setPreferredSize(new java.awt.Dimension(105, 35));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        btnPanel.add(btnTimKiem);

        btnChiTiet.setBackground(new java.awt.Color(0, 153, 153));
        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChiTiet.setMaximumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setMinimumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setPreferredSize(new java.awt.Dimension(105, 35));
        btnPanel.add(btnChiTiet);

        add(btnPanel, java.awt.BorderLayout.SOUTH);

        jPanel6.setMinimumSize(new java.awt.Dimension(829, 624));
        jPanel6.setPreferredSize(new java.awt.Dimension(829, 624));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 102, 102));
        jPanel7.setMinimumSize(new java.awt.Dimension(829, 312));
        jPanel7.setPreferredSize(new java.awt.Dimension(829, 220));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setMinimumSize(new java.awt.Dimension(829, 50));
        jPanel8.setPreferredSize(new java.awt.Dimension(829, 50));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nhập thông tin tìm kiếm");
        jPanel8.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel13.setMinimumSize(new java.awt.Dimension(829, 300));
        jPanel13.setPreferredSize(new java.awt.Dimension(829, 150));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.Y_AXIS));

        jPanel14.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel27.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel27.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel27.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Họ tên:");
        jLabel10.setAlignmentX(20.0F);
        jLabel10.setAlignmentY(20.0F);
        jPanel27.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel27, java.awt.BorderLayout.LINE_START);

        jPanel28.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel28.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jTextField5.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel28.add(jTextField5);

        jPanel14.add(jPanel28, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel14);

        jPanel16.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel29.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel29.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Giới tính:");
        jPanel29.add(jLabel11, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel29, java.awt.BorderLayout.LINE_START);

        jPanel30.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel30.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 3));

        jRadioButton3.setText("Nam");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel17.add(jRadioButton3);

        jRadioButton4.setText("Nữ");
        jPanel17.add(jRadioButton4);
        jPanel17.add(jLabel12);

        jLabel13.setText("       ");
        jPanel17.add(jLabel13);

        jPanel30.add(jPanel17);

        jPanel16.add(jPanel30, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel16);

        jPanel18.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel33.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel33.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel33.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("SĐT:");
        jPanel33.add(jLabel14, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel33, java.awt.BorderLayout.LINE_START);

        jPanel34.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel34.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel34.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtHoTen3.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel34.add(txtHoTen3);

        jPanel18.add(jPanel34, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel18);

        jPanel35.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel35.setLayout(new java.awt.BorderLayout());

        jPanel36.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel36.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel36.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Tuổi:");
        jPanel36.add(jLabel15, java.awt.BorderLayout.CENTER);

        jPanel35.add(jPanel36, java.awt.BorderLayout.LINE_START);

        jPanel37.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel37.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel37.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        txtHoTen5.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel37.add(txtHoTen5);

        jPanel35.add(jPanel37, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel35);

        jPanel7.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel38.setBackground(new java.awt.Color(255, 255, 153));
        jPanel38.setPreferredSize(new java.awt.Dimension(829, 420));
        jPanel38.setLayout(new java.awt.BorderLayout());

        jPanel39.setPreferredSize(new java.awt.Dimension(829, 525));
        jPanel39.setLayout(new java.awt.BorderLayout());

        jPanel40.setBackground(new java.awt.Color(0, 153, 153));
        jPanel40.setPreferredSize(new java.awt.Dimension(829, 50));
        jPanel40.setLayout(new java.awt.BorderLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Danh sách khách hàng");
        jPanel40.add(jLabel16, java.awt.BorderLayout.CENTER);

        jPanel39.add(jPanel40, java.awt.BorderLayout.PAGE_START);

        jPanel41.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã KH", "Tên KH", "Giới tính", "SĐT ", "Tuổi"
            }
        ));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(jTable2);

        jPanel41.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel39.add(jPanel41, java.awt.BorderLayout.CENTER);

        jPanel38.add(jPanel39, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel38, java.awt.BorderLayout.CENTER);

        btnPanel1.setBackground(new java.awt.Color(222, 222, 222));
        btnPanel1.setPreferredSize(new java.awt.Dimension(829, 50));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 8);
        flowLayout2.setAlignOnBaseline(true);
        btnPanel1.setLayout(flowLayout2);

        btnTimKiem1.setBackground(new java.awt.Color(0, 153, 153));
        btnTimKiem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem1.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem1.setText("Tìm kiếm");
        btnTimKiem1.setMaximumSize(new java.awt.Dimension(85, 35));
        btnTimKiem1.setMinimumSize(new java.awt.Dimension(85, 35));
        btnTimKiem1.setPreferredSize(new java.awt.Dimension(105, 35));
        btnTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiem1ActionPerformed(evt);
            }
        });
        btnPanel1.add(btnTimKiem1);

        btnChiTiet1.setBackground(new java.awt.Color(0, 153, 153));
        btnChiTiet1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTiet1.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTiet1.setText("Chi tiết");
        btnChiTiet1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChiTiet1.setMaximumSize(new java.awt.Dimension(85, 35));
        btnChiTiet1.setMinimumSize(new java.awt.Dimension(85, 35));
        btnChiTiet1.setPreferredSize(new java.awt.Dimension(105, 35));
        btnPanel1.add(btnChiTiet1);

        jPanel6.add(btnPanel1, java.awt.BorderLayout.SOUTH);

        add(jPanel6, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void btnTimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnChiTiet1;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JPanel btnPanel1;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTimKiem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtHoTen2;
    private javax.swing.JTextField txtHoTen3;
    private javax.swing.JTextField txtHoTen4;
    private javax.swing.JTextField txtHoTen5;
    // End of variables declaration//GEN-END:variables
}
