/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.page;
import DAO.NhaCungCapDAO;
import Entity.NhaCungCap;
import GUI.form.formThemNCC;
import GUI.form.formThongTinNCC;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class frmSearchNhaCungCap extends javax.swing.JPanel {

    private int startIndex;

    /**
     * Creates new form SearchNhaCungCap
     */
    public frmSearchNhaCungCap() {
         initComponents();
         configureTable();
         startIndex = 0;
         loadDataToTable();
         // Thêm sự kiện cuộn bảng
         jScrollPane1.getVerticalScrollBar().addAdjustmentListener(e -> {
             JScrollBar vertical = jScrollPane1.getVerticalScrollBar();
             int max = vertical.getMaximum();
             int current = vertical.getValue();
             int visible = vertical.getVisibleAmount();
 
             // Kiểm tra nếu người dùng đã cuộn đến cuối bảng
             if (current + visible >= max) {
                 startIndex += 13 ; // Tăng chỉ mục bắt đầu để tải dữ liệu tiếp theo
                 loadDataToTable();  // Tải thêm dữ liệu
             }
 
         });
    }
    private void configureTable() {
         // Ngăn không cho phép người dùng chỉnh sửa bảng
         jTable1.setDefaultEditor(Object.class, null);  // Điều này vô hiệu hóa khả năng chỉnh sửa của bất kỳ ô nào trong bảng.
 
         // Căn giữa cho tất cả các cell trong bảng
         DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
         centerRenderer.setHorizontalAlignment(JLabel.CENTER);
 
         // Căn giữa cho từng cột
         for (int i = 0; i < jTable1.getColumnCount(); i++) {
             jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
         }
 
         // Ngăn không cho phép chọn nhiều dòng
         jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
     }
    private void loadDataToTable() {
         // Lấy dữ liệu thuốc với batch tiếp theo (10 dòng)
         SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
             @Override
             protected Void doInBackground() throws Exception {
                 // Lấy danh sách NCC từ cơ sở dữ liệu (10 dòng bắt đầu từ startIndex)
                 List<NhaCungCap> nccList = NhaCungCapDAO.getNhaCungCapBatch(startIndex, 13);  // startIndex là chỉ mục bắt đầu
                 SwingUtilities.invokeLater(() -> {
                     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
 
                     // Chỉ thêm dữ liệu mới vào bảng, không xóa dữ liệu cũ
                     for (NhaCungCap ncc : nccList) {
                         model.addRow(new Object[]{
                             ncc.getId(),
                             ncc.getTenNhaCungCap(),
                             ncc.getDiaChi(),
                             ncc.getSdt(),
                         });
                     }
                 });
                 return null;
             }
         };
         worker.execute();
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        txtTenNCC = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        txtDiaChi = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        txtSDT = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnPanel = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(829, 624));
        setPreferredSize(new java.awt.Dimension(829, 624));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(829, 262));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(0, 120, 92));
        jPanel6.setPreferredSize(new java.awt.Dimension(829, 50));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập thông tin tìm kiếm");
        jPanel6.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel19.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel19.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel19.setLayout(new java.awt.BorderLayout());
        jPanel9.add(jPanel19, java.awt.BorderLayout.LINE_START);

        jPanel20.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel20.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));
        jPanel9.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9);

        jPanel12.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel22.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel22.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel22.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Tên nhà cung cấp:");
        jLabel4.setAlignmentX(20.0F);
        jLabel4.setAlignmentY(20.0F);
        jPanel22.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel22, java.awt.BorderLayout.LINE_START);

        jPanel23.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel23.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtTenNCC.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel23.add(txtTenNCC);

        jPanel12.add(jPanel23, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel12);

        jPanel13.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel24.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel24.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel24.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Địa chỉ:");
        jLabel5.setAlignmentX(20.0F);
        jLabel5.setAlignmentY(20.0F);
        jPanel24.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel24, java.awt.BorderLayout.LINE_START);

        jPanel25.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel25.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtDiaChi.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel25.add(txtDiaChi);

        jPanel13.add(jPanel25, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel13);

        jPanel14.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel26.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel26.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("SĐT:");
        jLabel8.setAlignmentX(20.0F);
        jLabel8.setAlignmentY(20.0F);
        jPanel26.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel26, java.awt.BorderLayout.LINE_START);

        jPanel27.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel27.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtSDT.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel27.add(txtSDT);

        jPanel14.add(jPanel27, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel14);

        jPanel15.setMinimumSize(new java.awt.Dimension(829, 38));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel28.setMinimumSize(new java.awt.Dimension(300, 38));
        jPanel28.setPreferredSize(new java.awt.Dimension(500, 38));
        jPanel28.setLayout(new java.awt.BorderLayout());
        jPanel15.add(jPanel28, java.awt.BorderLayout.LINE_START);

        jPanel29.setMinimumSize(new java.awt.Dimension(669, 38));
        jPanel29.setPreferredSize(new java.awt.Dimension(669, 38));
        jPanel29.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));
        jPanel15.add(jPanel29, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel15);

        jPanel5.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(829, 312));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 120, 92));
        jPanel1.setPreferredSize(new java.awt.Dimension(829, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Danh sách nhà cung cấp");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NCC", "Tên NCC", "Địa chỉ NCC", "SĐT NCC"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.CENTER);

        btnPanel.setBackground(new java.awt.Color(222, 222, 222));
        btnPanel.setPreferredSize(new java.awt.Dimension(829, 50));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 8);
        flowLayout2.setAlignOnBaseline(true);
        btnPanel.setLayout(flowLayout2);

        btnTimKiem.setBackground(new java.awt.Color(0, 120, 92));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setMaximumSize(new java.awt.Dimension(85, 35));
        btnTimKiem.setMinimumSize(new java.awt.Dimension(85, 35));
        btnTimKiem.setPreferredSize(new java.awt.Dimension(105, 35));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        btnPanel.add(btnTimKiem);

        btnChiTiet.setBackground(new java.awt.Color(0, 120, 92));
        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChiTiet.setMaximumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setMinimumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setPreferredSize(new java.awt.Dimension(105, 35));
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });
        btnPanel.add(btnChiTiet);

        add(btnPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String tenNCC = txtTenNCC.getText().trim();  // Họ tên
        String diaChi = txtDiaChi.getText().trim();
        String sdt = txtSDT.getText().trim();  // SĐT
        // Tìm kiếm nhân viên theo các tiêu chí
        List<NhaCungCap> results = NhaCungCapDAO.searchNhaCungCap(tenNCC, diaChi, sdt);

        // Cập nhật bảng với kết quả tìm kiếm
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);  // Xóa dữ liệu cũ trong bảng

        // Thêm kết quả tìm kiếm vào bảng
        for (NhaCungCap ncc: results) {
            model.addRow(new Object[]{
                ncc.getId(),
                ncc.getTenNhaCungCap(),
                ncc.getDiaChi(),
                ncc.getSdt(),
            });
        }

        // Nếu không có kết quả, hiển thị thông báo
        if (results.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhà cung cấp phù hợp!");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();  // Lấy dòng được chọn trong bảng

        if (selectedRow != -1) {
            // Lấy mã thuốc từ cột đầu tiên (mã thuốc)
            String maNCC = jTable1.getValueAt(selectedRow, 0).toString();

            // Mở form "Thông tin thuốc" và truyền mã thuốc vào constructor
            JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            formThongTinNCC dialog = new formThongTinNCC(parentFrame, true, maNCC);  // Truyền mã thuốc vào constructor
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà cung cấp để xem chi tiết!");
        }
    }//GEN-LAST:event_btnChiTietActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNCC;
    // End of variables declaration//GEN-END:variables

    private void formThongTinNCC() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
